#############################################################################
# Makefile for building: AutoUrine
# Generated by qmake (2.01a) (Qt 4.8.6) on: ?? 5? 2 13:13:19 2018
# Project:  AutoUrine.pro
# Template: app
# Command: /opt/qt-m6g2c/bin/qmake -o Makefile AutoUrine.pro
#############################################################################

####### Compiler, tools and options

CC            = arm-linux-gnueabihf-gcc -lts
CXX           = arm-linux-gnueabihf-g++ -lts
DEFINES       = -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/opt/qt-m6g2c/mkspecs/qws/linux-arm-gnueabi-g++ -I. -I/opt/qt-m6g2c/include/QtCore -I/opt/qt-m6g2c/include/QtNetwork -I/opt/qt-m6g2c/include/QtGui -I/opt/qt-m6g2c/include/QtSql -I/opt/qt-m6g2c/include -I. -I. -IUI -I/opt/tslib/include
LINK          = arm-linux-gnueabihf-g++ -lts
LFLAGS        = -Wl,-O1 -Wl,-rpath,/opt/qt-m6g2c/lib
LIBS          = $(SUBLIBS)  -L/opt/tslib/lib -L/opt/qt-m6g2c/lib -lQtSql -L/opt/tslib/lib -L/opt/qt-m6g2c/lib -lQtGui -lQtNetwork -lQtCore -lrt -lpthread 
AR            = arm-linux-gnueabihf-ar cqs
RANLIB        = 
QMAKE         = /opt/qt-m6g2c/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = arm-linux-gnueabihf-strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = App.cpp \
		calibratedialog.cpp \
		calibratemodel.cpp \
		calibrateobservermodel.cpp \
		databasehelper.cpp \
		frminput.cpp \
		frmmessagebox.cpp \
		iconhelper.cpp \
		itemmodel.cpp \
		itemparametermodel.cpp \
		main.cpp \
		mainbussniessview.cpp \
		mainbuttondialog.cpp \
		maintenancedialog.cpp \
		mainwindow.cpp \
		parameterdialog.cpp \
		patientmodel.cpp \
		posix_qextserialport.cpp \
		qc_subitemmodel.cpp \
		qextserialbase.cpp \
		qualitycontroldialog.cpp \
		qualitycontrolmodel.cpp \
		querydialog.cpp \
		sampletypemodel.cpp \
		serialportctrl.cpp \
		serialportthread.cpp \
		stopthread.cpp \
		systemdialog.cpp \
		testingdialog.cpp \
		testingthread.cpp \
		testresultmodel.cpp \
		whitethread.cpp moc_calibratedialog.cpp \
		moc_frminput.cpp \
		moc_frmmessagebox.cpp \
		moc_mainbussniessview.cpp \
		moc_mainbuttondialog.cpp \
		moc_maintenancedialog.cpp \
		moc_mainwindow.cpp \
		moc_parameterdialog.cpp \
		moc_qextserialbase.cpp \
		moc_qprogressdialog.cpp \
		moc_qualitycontroldialog.cpp \
		moc_querydialog.cpp \
		moc_serialportctrl.cpp \
		moc_serialportthread.cpp \
		moc_stopthread.cpp \
		moc_systemdialog.cpp \
		moc_testingdialog.cpp \
		moc_testingthread.cpp \
		moc_whitethread.cpp \
		qrc_rc.cpp
OBJECTS       = App.o \
		calibratedialog.o \
		calibratemodel.o \
		calibrateobservermodel.o \
		databasehelper.o \
		frminput.o \
		frmmessagebox.o \
		iconhelper.o \
		itemmodel.o \
		itemparametermodel.o \
		main.o \
		mainbussniessview.o \
		mainbuttondialog.o \
		maintenancedialog.o \
		mainwindow.o \
		parameterdialog.o \
		patientmodel.o \
		posix_qextserialport.o \
		qc_subitemmodel.o \
		qextserialbase.o \
		qualitycontroldialog.o \
		qualitycontrolmodel.o \
		querydialog.o \
		sampletypemodel.o \
		serialportctrl.o \
		serialportthread.o \
		stopthread.o \
		systemdialog.o \
		testingdialog.o \
		testingthread.o \
		testresultmodel.o \
		whitethread.o \
		moc_calibratedialog.o \
		moc_frminput.o \
		moc_frmmessagebox.o \
		moc_mainbussniessview.o \
		moc_mainbuttondialog.o \
		moc_maintenancedialog.o \
		moc_mainwindow.o \
		moc_parameterdialog.o \
		moc_qextserialbase.o \
		moc_qprogressdialog.o \
		moc_qualitycontroldialog.o \
		moc_querydialog.o \
		moc_serialportctrl.o \
		moc_serialportthread.o \
		moc_stopthread.o \
		moc_systemdialog.o \
		moc_testingdialog.o \
		moc_testingthread.o \
		moc_whitethread.o \
		qrc_rc.o
DIST          = /opt/qt-m6g2c/mkspecs/common/unix.conf \
		/opt/qt-m6g2c/mkspecs/common/linux.conf \
		/opt/qt-m6g2c/mkspecs/common/gcc-base.conf \
		/opt/qt-m6g2c/mkspecs/common/gcc-base-unix.conf \
		/opt/qt-m6g2c/mkspecs/common/g++-base.conf \
		/opt/qt-m6g2c/mkspecs/common/g++-unix.conf \
		/opt/qt-m6g2c/mkspecs/common/qws.conf \
		/opt/qt-m6g2c/mkspecs/qconfig.pri \
		/opt/qt-m6g2c/mkspecs/features/qt_functions.prf \
		/opt/qt-m6g2c/mkspecs/features/qt_config.prf \
		/opt/qt-m6g2c/mkspecs/features/exclusive_builds.prf \
		/opt/qt-m6g2c/mkspecs/features/default_pre.prf \
		/opt/qt-m6g2c/mkspecs/features/release.prf \
		/opt/qt-m6g2c/mkspecs/features/default_post.prf \
		/opt/qt-m6g2c/mkspecs/features/shared.prf \
		/opt/qt-m6g2c/mkspecs/features/warn_on.prf \
		/opt/qt-m6g2c/mkspecs/features/qt.prf \
		/opt/qt-m6g2c/mkspecs/features/unix/thread.prf \
		/opt/qt-m6g2c/mkspecs/features/moc.prf \
		/opt/qt-m6g2c/mkspecs/features/resources.prf \
		/opt/qt-m6g2c/mkspecs/features/uic.prf \
		/opt/qt-m6g2c/mkspecs/features/yacc.prf \
		/opt/qt-m6g2c/mkspecs/features/lex.prf \
		/opt/qt-m6g2c/mkspecs/features/include_source_dir.prf \
		AutoUrine.pro
QMAKE_TARGET  = AutoUrine
DESTDIR       = 
TARGET        = AutoUrine

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): UI/ui_calibratedialog.h UI/ui_frminput.h UI/ui_frmmessagebox.h UI/ui_mainbuttondialog.h UI/ui_maintenancedialog.h UI/ui_mainwindow.h UI/ui_parameterdialog.h UI/ui_qprogressdialog.h UI/ui_qualitycontroldialog.h UI/ui_querydialog.h UI/ui_systemdialog.h UI/ui_testingdialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: AutoUrine.pro  /opt/qt-m6g2c/mkspecs/qws/linux-arm-gnueabi-g++/qmake.conf /opt/qt-m6g2c/mkspecs/common/unix.conf \
		/opt/qt-m6g2c/mkspecs/common/linux.conf \
		/opt/qt-m6g2c/mkspecs/common/gcc-base.conf \
		/opt/qt-m6g2c/mkspecs/common/gcc-base-unix.conf \
		/opt/qt-m6g2c/mkspecs/common/g++-base.conf \
		/opt/qt-m6g2c/mkspecs/common/g++-unix.conf \
		/opt/qt-m6g2c/mkspecs/common/qws.conf \
		/opt/qt-m6g2c/mkspecs/qconfig.pri \
		/opt/qt-m6g2c/mkspecs/features/qt_functions.prf \
		/opt/qt-m6g2c/mkspecs/features/qt_config.prf \
		/opt/qt-m6g2c/mkspecs/features/exclusive_builds.prf \
		/opt/qt-m6g2c/mkspecs/features/default_pre.prf \
		/opt/qt-m6g2c/mkspecs/features/release.prf \
		/opt/qt-m6g2c/mkspecs/features/default_post.prf \
		/opt/qt-m6g2c/mkspecs/features/shared.prf \
		/opt/qt-m6g2c/mkspecs/features/warn_on.prf \
		/opt/qt-m6g2c/mkspecs/features/qt.prf \
		/opt/qt-m6g2c/mkspecs/features/unix/thread.prf \
		/opt/qt-m6g2c/mkspecs/features/moc.prf \
		/opt/qt-m6g2c/mkspecs/features/resources.prf \
		/opt/qt-m6g2c/mkspecs/features/uic.prf \
		/opt/qt-m6g2c/mkspecs/features/yacc.prf \
		/opt/qt-m6g2c/mkspecs/features/lex.prf \
		/opt/qt-m6g2c/mkspecs/features/include_source_dir.prf \
		/opt/qt-m6g2c/lib/libQtSql.prl \
		/opt/qt-m6g2c/lib/libQtCore.prl \
		/opt/qt-m6g2c/lib/libQtGui.prl \
		/opt/qt-m6g2c/lib/libQtNetwork.prl
	$(QMAKE) -o Makefile AutoUrine.pro
/opt/qt-m6g2c/mkspecs/common/unix.conf:
/opt/qt-m6g2c/mkspecs/common/linux.conf:
/opt/qt-m6g2c/mkspecs/common/gcc-base.conf:
/opt/qt-m6g2c/mkspecs/common/gcc-base-unix.conf:
/opt/qt-m6g2c/mkspecs/common/g++-base.conf:
/opt/qt-m6g2c/mkspecs/common/g++-unix.conf:
/opt/qt-m6g2c/mkspecs/common/qws.conf:
/opt/qt-m6g2c/mkspecs/qconfig.pri:
/opt/qt-m6g2c/mkspecs/features/qt_functions.prf:
/opt/qt-m6g2c/mkspecs/features/qt_config.prf:
/opt/qt-m6g2c/mkspecs/features/exclusive_builds.prf:
/opt/qt-m6g2c/mkspecs/features/default_pre.prf:
/opt/qt-m6g2c/mkspecs/features/release.prf:
/opt/qt-m6g2c/mkspecs/features/default_post.prf:
/opt/qt-m6g2c/mkspecs/features/shared.prf:
/opt/qt-m6g2c/mkspecs/features/warn_on.prf:
/opt/qt-m6g2c/mkspecs/features/qt.prf:
/opt/qt-m6g2c/mkspecs/features/unix/thread.prf:
/opt/qt-m6g2c/mkspecs/features/moc.prf:
/opt/qt-m6g2c/mkspecs/features/resources.prf:
/opt/qt-m6g2c/mkspecs/features/uic.prf:
/opt/qt-m6g2c/mkspecs/features/yacc.prf:
/opt/qt-m6g2c/mkspecs/features/lex.prf:
/opt/qt-m6g2c/mkspecs/features/include_source_dir.prf:
/opt/qt-m6g2c/lib/libQtSql.prl:
/opt/qt-m6g2c/lib/libQtCore.prl:
/opt/qt-m6g2c/lib/libQtGui.prl:
/opt/qt-m6g2c/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile AutoUrine.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/AutoUrine1.0.0 || $(MKDIR) .tmp/AutoUrine1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/AutoUrine1.0.0/ && $(COPY_FILE) --parents App.h calibratedialog.h calibratemodel.h calibrateobservermodel.h databasehelper.h frminput.h frmmessagebox.h iconhelper.h itemmodel.h itemparametermodel.h mainbussniessview.h mainbuttondialog.h maintenancedialog.h mainwindow.h myhelper.h parameterdialog.h patientmodel.h posix_qextserialport.h qc_subitemmodel.h qextserialbase.h qprogressdialog.h qualitycontroldialog.h qualitycontrolmodel.h querydialog.h sampletypemodel.h serialportctrl.h serialportthread.h stopthread.h systemdialog.h testingdialog.h testingthread.h testresultmodel.h whitethread.h .tmp/AutoUrine1.0.0/ && $(COPY_FILE) --parents rc.qrc .tmp/AutoUrine1.0.0/ && $(COPY_FILE) --parents App.cpp calibratedialog.cpp calibratemodel.cpp calibrateobservermodel.cpp databasehelper.cpp frminput.cpp frmmessagebox.cpp iconhelper.cpp itemmodel.cpp itemparametermodel.cpp main.cpp mainbussniessview.cpp mainbuttondialog.cpp maintenancedialog.cpp mainwindow.cpp parameterdialog.cpp patientmodel.cpp posix_qextserialport.cpp qc_subitemmodel.cpp qextserialbase.cpp qualitycontroldialog.cpp qualitycontrolmodel.cpp querydialog.cpp sampletypemodel.cpp serialportctrl.cpp serialportthread.cpp stopthread.cpp systemdialog.cpp testingdialog.cpp testingthread.cpp testresultmodel.cpp whitethread.cpp .tmp/AutoUrine1.0.0/ && $(COPY_FILE) --parents calibratedialog.ui frminput.ui frmmessagebox.ui mainbuttondialog.ui maintenancedialog.ui mainwindow.ui parameterdialog.ui qprogressdialog.ui qualitycontroldialog.ui querydialog.ui systemdialog.ui testingdialog.ui .tmp/AutoUrine1.0.0/ && $(COPY_FILE) --parents chinese.ts english.ts chinese.ts english.ts .tmp/AutoUrine1.0.0/ && (cd `dirname .tmp/AutoUrine1.0.0` && $(TAR) AutoUrine1.0.0.tar AutoUrine1.0.0 && $(COMPRESS) AutoUrine1.0.0.tar) && $(MOVE) `dirname .tmp/AutoUrine1.0.0`/AutoUrine1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/AutoUrine1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_calibratedialog.cpp moc_frminput.cpp moc_frmmessagebox.cpp moc_mainbussniessview.cpp moc_mainbuttondialog.cpp moc_maintenancedialog.cpp moc_mainwindow.cpp moc_parameterdialog.cpp moc_qextserialbase.cpp moc_qprogressdialog.cpp moc_qualitycontroldialog.cpp moc_querydialog.cpp moc_serialportctrl.cpp moc_serialportthread.cpp moc_stopthread.cpp moc_systemdialog.cpp moc_testingdialog.cpp moc_testingthread.cpp moc_whitethread.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_calibratedialog.cpp moc_frminput.cpp moc_frmmessagebox.cpp moc_mainbussniessview.cpp moc_mainbuttondialog.cpp moc_maintenancedialog.cpp moc_mainwindow.cpp moc_parameterdialog.cpp moc_qextserialbase.cpp moc_qprogressdialog.cpp moc_qualitycontroldialog.cpp moc_querydialog.cpp moc_serialportctrl.cpp moc_serialportthread.cpp moc_stopthread.cpp moc_systemdialog.cpp moc_testingdialog.cpp moc_testingthread.cpp moc_whitethread.cpp
moc_calibratedialog.cpp: calibrateobservermodel.h \
		calibratedialog.h
	/opt/qt-m6g2c/bin/moc $(DEFINES) $(INCPATH) calibratedialog.h -o moc_calibratedialog.cpp

moc_frminput.cpp: frminput.h
	/opt/qt-m6g2c/bin/moc $(DEFINES) $(INCPATH) frminput.h -o moc_frminput.cpp

moc_frmmessagebox.cpp: frmmessagebox.h
	/opt/qt-m6g2c/bin/moc $(DEFINES) $(INCPATH) frmmessagebox.h -o moc_frmmessagebox.cpp

moc_mainbussniessview.cpp: patientmodel.h \
		itemmodel.h \
		qc_subitemmodel.h \
		qualitycontrolmodel.h \
		itemparametermodel.h \
		calibratemodel.h \
		sampletypemodel.h \
		testresultmodel.h \
		App.h \
		calibrateobservermodel.h \
		mainbussniessview.h
	/opt/qt-m6g2c/bin/moc $(DEFINES) $(INCPATH) mainbussniessview.h -o moc_mainbussniessview.cpp

moc_mainbuttondialog.cpp: mainbuttondialog.h
	/opt/qt-m6g2c/bin/moc $(DEFINES) $(INCPATH) mainbuttondialog.h -o moc_mainbuttondialog.cpp

moc_maintenancedialog.cpp: maintenancedialog.h
	/opt/qt-m6g2c/bin/moc $(DEFINES) $(INCPATH) maintenancedialog.h -o moc_maintenancedialog.cpp

moc_mainwindow.cpp: mainbuttondialog.h \
		mainwindow.h
	/opt/qt-m6g2c/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_parameterdialog.cpp: parameterdialog.h
	/opt/qt-m6g2c/bin/moc $(DEFINES) $(INCPATH) parameterdialog.h -o moc_parameterdialog.cpp

moc_qextserialbase.cpp: qextserialbase.h
	/opt/qt-m6g2c/bin/moc $(DEFINES) $(INCPATH) qextserialbase.h -o moc_qextserialbase.cpp

moc_qprogressdialog.cpp: qprogressdialog.h
	/opt/qt-m6g2c/bin/moc $(DEFINES) $(INCPATH) qprogressdialog.h -o moc_qprogressdialog.cpp

moc_qualitycontroldialog.cpp: qualitycontroldialog.h
	/opt/qt-m6g2c/bin/moc $(DEFINES) $(INCPATH) qualitycontroldialog.h -o moc_qualitycontroldialog.cpp

moc_querydialog.cpp: querydialog.h
	/opt/qt-m6g2c/bin/moc $(DEFINES) $(INCPATH) querydialog.h -o moc_querydialog.cpp

moc_serialportctrl.cpp: serialportctrl.h
	/opt/qt-m6g2c/bin/moc $(DEFINES) $(INCPATH) serialportctrl.h -o moc_serialportctrl.cpp

moc_serialportthread.cpp: serialportthread.h
	/opt/qt-m6g2c/bin/moc $(DEFINES) $(INCPATH) serialportthread.h -o moc_serialportthread.cpp

moc_stopthread.cpp: stopthread.h
	/opt/qt-m6g2c/bin/moc $(DEFINES) $(INCPATH) stopthread.h -o moc_stopthread.cpp

moc_systemdialog.cpp: systemdialog.h
	/opt/qt-m6g2c/bin/moc $(DEFINES) $(INCPATH) systemdialog.h -o moc_systemdialog.cpp

moc_testingdialog.cpp: patientmodel.h \
		App.h \
		serialportctrl.h \
		testingdialog.h
	/opt/qt-m6g2c/bin/moc $(DEFINES) $(INCPATH) testingdialog.h -o moc_testingdialog.cpp

moc_testingthread.cpp: testingthread.h
	/opt/qt-m6g2c/bin/moc $(DEFINES) $(INCPATH) testingthread.h -o moc_testingthread.cpp

moc_whitethread.cpp: whitethread.h
	/opt/qt-m6g2c/bin/moc $(DEFINES) $(INCPATH) whitethread.h -o moc_whitethread.cpp

compiler_rcc_make_all: qrc_rc.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_rc.cpp
qrc_rc.cpp: rc.qrc \
		pinyin/english.qm \
		pinyin/chinese.qm \
		pinyin/syszuxpinyin \
		image/Background.png \
		image/error.png \
		image/Print.png \
		image/Stop1.png \
		image/WarningIcon.png \
		image/sub-line_vertical.png \
		image/checkbox_unchecked.png \
		image/Query.png \
		image/sub-line_horizontal.png \
		image/black.css \
		image/QualityControl.png \
		image/checkbox_checked.png \
		image/add-line_horizontal.png \
		image/Manual.png \
		image/array_down.png \
		image/Shutdown.png \
		image/Compute.png \
		image/info.png \
		image/gray.css \
		image/blue.css \
		image/Delete.png \
		image/logo.png \
		image/Title.jpg \
		image/Run1.png \
		image/Run.png \
		image/Save.png \
		image/question.png \
		image/Parameter.png \
		image/radio_normal.png \
		image/radio_selected.png \
		image/Stop.png \
		image/CompanyTitle.png \
		image/fontawesome-webfont.ttf \
		image/add-line_vertical.png \
		image/System.png \
		image/libtest.so.1.0.0 \
		image/navy.css \
		image/Testing.png \
		image/Calibrate.png \
		image/History.png \
		image/logo.ico \
		image/Maintainance.png
	/opt/qt-m6g2c/bin/rcc -name rc rc.qrc -o qrc_rc.cpp

compiler_image_collection_make_all: UI/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) UI/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: UI/ui_calibratedialog.h UI/ui_frminput.h UI/ui_frmmessagebox.h UI/ui_mainbuttondialog.h UI/ui_maintenancedialog.h UI/ui_mainwindow.h UI/ui_parameterdialog.h UI/ui_qprogressdialog.h UI/ui_qualitycontroldialog.h UI/ui_querydialog.h UI/ui_systemdialog.h UI/ui_testingdialog.h
compiler_uic_clean:
	-$(DEL_FILE) UI/ui_calibratedialog.h UI/ui_frminput.h UI/ui_frmmessagebox.h UI/ui_mainbuttondialog.h UI/ui_maintenancedialog.h UI/ui_mainwindow.h UI/ui_parameterdialog.h UI/ui_qprogressdialog.h UI/ui_qualitycontroldialog.h UI/ui_querydialog.h UI/ui_systemdialog.h UI/ui_testingdialog.h
UI/ui_calibratedialog.h: calibratedialog.ui
	/opt/qt-m6g2c/bin/uic calibratedialog.ui -o UI/ui_calibratedialog.h

UI/ui_frminput.h: frminput.ui
	/opt/qt-m6g2c/bin/uic frminput.ui -o UI/ui_frminput.h

UI/ui_frmmessagebox.h: frmmessagebox.ui
	/opt/qt-m6g2c/bin/uic frmmessagebox.ui -o UI/ui_frmmessagebox.h

UI/ui_mainbuttondialog.h: mainbuttondialog.ui
	/opt/qt-m6g2c/bin/uic mainbuttondialog.ui -o UI/ui_mainbuttondialog.h

UI/ui_maintenancedialog.h: maintenancedialog.ui
	/opt/qt-m6g2c/bin/uic maintenancedialog.ui -o UI/ui_maintenancedialog.h

UI/ui_mainwindow.h: mainwindow.ui
	/opt/qt-m6g2c/bin/uic mainwindow.ui -o UI/ui_mainwindow.h

UI/ui_parameterdialog.h: parameterdialog.ui
	/opt/qt-m6g2c/bin/uic parameterdialog.ui -o UI/ui_parameterdialog.h

UI/ui_qprogressdialog.h: qprogressdialog.ui
	/opt/qt-m6g2c/bin/uic qprogressdialog.ui -o UI/ui_qprogressdialog.h

UI/ui_qualitycontroldialog.h: qualitycontroldialog.ui
	/opt/qt-m6g2c/bin/uic qualitycontroldialog.ui -o UI/ui_qualitycontroldialog.h

UI/ui_querydialog.h: querydialog.ui
	/opt/qt-m6g2c/bin/uic querydialog.ui -o UI/ui_querydialog.h

UI/ui_systemdialog.h: systemdialog.ui
	/opt/qt-m6g2c/bin/uic systemdialog.ui -o UI/ui_systemdialog.h

UI/ui_testingdialog.h: testingdialog.ui
	/opt/qt-m6g2c/bin/uic testingdialog.ui -o UI/ui_testingdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

App.o: App.cpp App.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o App.o App.cpp

calibratedialog.o: calibratedialog.cpp calibratedialog.h \
		calibrateobservermodel.h \
		ui_calibratedialog.h \
		mainbussniessview.h \
		patientmodel.h \
		itemmodel.h \
		qc_subitemmodel.h \
		qualitycontrolmodel.h \
		itemparametermodel.h \
		calibratemodel.h \
		sampletypemodel.h \
		testresultmodel.h \
		App.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calibratedialog.o calibratedialog.cpp

calibratemodel.o: calibratemodel.cpp calibratemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calibratemodel.o calibratemodel.cpp

calibrateobservermodel.o: calibrateobservermodel.cpp calibrateobservermodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calibrateobservermodel.o calibrateobservermodel.cpp

databasehelper.o: databasehelper.cpp databasehelper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o databasehelper.o databasehelper.cpp

frminput.o: frminput.cpp frminput.h \
		ui_frminput.h \
		myhelper.h \
		frmmessagebox.h \
		iconhelper.h \
		App.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o frminput.o frminput.cpp

frmmessagebox.o: frmmessagebox.cpp frmmessagebox.h \
		ui_frmmessagebox.h \
		iconhelper.h \
		myhelper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o frmmessagebox.o frmmessagebox.cpp

iconhelper.o: iconhelper.cpp iconhelper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o iconhelper.o iconhelper.cpp

itemmodel.o: itemmodel.cpp itemmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o itemmodel.o itemmodel.cpp

itemparametermodel.o: itemparametermodel.cpp itemparametermodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o itemparametermodel.o itemparametermodel.cpp

main.o: main.cpp mainwindow.h \
		mainbuttondialog.h \
		myhelper.h \
		frmmessagebox.h \
		frminput.h \
		App.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainbussniessview.o: mainbussniessview.cpp mainbussniessview.h \
		patientmodel.h \
		itemmodel.h \
		qc_subitemmodel.h \
		qualitycontrolmodel.h \
		itemparametermodel.h \
		calibratemodel.h \
		sampletypemodel.h \
		testresultmodel.h \
		App.h \
		calibrateobservermodel.h \
		databasehelper.h \
		testingthread.h \
		myhelper.h \
		frmmessagebox.h \
		stopthread.h \
		whitethread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainbussniessview.o mainbussniessview.cpp

mainbuttondialog.o: mainbuttondialog.cpp mainbuttondialog.h \
		ui_mainbuttondialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainbuttondialog.o mainbuttondialog.cpp

maintenancedialog.o: maintenancedialog.cpp maintenancedialog.h \
		ui_maintenancedialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maintenancedialog.o maintenancedialog.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		mainbuttondialog.h \
		ui_mainwindow.h \
		iconhelper.h \
		myhelper.h \
		frmmessagebox.h \
		testingdialog.h \
		patientmodel.h \
		App.h \
		serialportctrl.h \
		mainbussniessview.h \
		itemmodel.h \
		qc_subitemmodel.h \
		qualitycontrolmodel.h \
		itemparametermodel.h \
		calibratemodel.h \
		sampletypemodel.h \
		testresultmodel.h \
		calibrateobservermodel.h \
		querydialog.h \
		qualitycontroldialog.h \
		parameterdialog.h \
		calibratedialog.h \
		systemdialog.h \
		maintenancedialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

parameterdialog.o: parameterdialog.cpp parameterdialog.h \
		ui_parameterdialog.h \
		mainbussniessview.h \
		patientmodel.h \
		itemmodel.h \
		qc_subitemmodel.h \
		qualitycontrolmodel.h \
		itemparametermodel.h \
		calibratemodel.h \
		sampletypemodel.h \
		testresultmodel.h \
		App.h \
		calibrateobservermodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parameterdialog.o parameterdialog.cpp

patientmodel.o: patientmodel.cpp patientmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o patientmodel.o patientmodel.cpp

posix_qextserialport.o: posix_qextserialport.cpp posix_qextserialport.h \
		qextserialbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o posix_qextserialport.o posix_qextserialport.cpp

qc_subitemmodel.o: qc_subitemmodel.cpp qc_subitemmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qc_subitemmodel.o qc_subitemmodel.cpp

qextserialbase.o: qextserialbase.cpp qextserialbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qextserialbase.o qextserialbase.cpp

qualitycontroldialog.o: qualitycontroldialog.cpp qualitycontroldialog.h \
		ui_qualitycontroldialog.h \
		mainbussniessview.h \
		patientmodel.h \
		itemmodel.h \
		qc_subitemmodel.h \
		qualitycontrolmodel.h \
		itemparametermodel.h \
		calibratemodel.h \
		sampletypemodel.h \
		testresultmodel.h \
		App.h \
		calibrateobservermodel.h \
		myhelper.h \
		frmmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qualitycontroldialog.o qualitycontroldialog.cpp

qualitycontrolmodel.o: qualitycontrolmodel.cpp qualitycontrolmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qualitycontrolmodel.o qualitycontrolmodel.cpp

querydialog.o: querydialog.cpp querydialog.h \
		ui_querydialog.h \
		myhelper.h \
		frmmessagebox.h \
		mainbussniessview.h \
		patientmodel.h \
		itemmodel.h \
		qc_subitemmodel.h \
		qualitycontrolmodel.h \
		itemparametermodel.h \
		calibratemodel.h \
		sampletypemodel.h \
		testresultmodel.h \
		App.h \
		calibrateobservermodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o querydialog.o querydialog.cpp

sampletypemodel.o: sampletypemodel.cpp sampletypemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sampletypemodel.o sampletypemodel.cpp

serialportctrl.o: serialportctrl.cpp serialportctrl.h \
		posix_qextserialport.h \
		qextserialbase.h \
		serialportthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serialportctrl.o serialportctrl.cpp

serialportthread.o: serialportthread.cpp serialportthread.h \
		posix_qextserialport.h \
		qextserialbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serialportthread.o serialportthread.cpp

stopthread.o: stopthread.cpp stopthread.h \
		App.h \
		mainbussniessview.h \
		patientmodel.h \
		itemmodel.h \
		qc_subitemmodel.h \
		qualitycontrolmodel.h \
		itemparametermodel.h \
		calibratemodel.h \
		sampletypemodel.h \
		testresultmodel.h \
		calibrateobservermodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stopthread.o stopthread.cpp

systemdialog.o: systemdialog.cpp systemdialog.h \
		ui_systemdialog.h \
		mainbussniessview.h \
		patientmodel.h \
		itemmodel.h \
		qc_subitemmodel.h \
		qualitycontrolmodel.h \
		itemparametermodel.h \
		calibratemodel.h \
		sampletypemodel.h \
		testresultmodel.h \
		App.h \
		calibrateobservermodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o systemdialog.o systemdialog.cpp

testingdialog.o: testingdialog.cpp testingdialog.h \
		patientmodel.h \
		App.h \
		serialportctrl.h \
		ui_testingdialog.h \
		mainbussniessview.h \
		itemmodel.h \
		qc_subitemmodel.h \
		qualitycontrolmodel.h \
		itemparametermodel.h \
		calibratemodel.h \
		sampletypemodel.h \
		testresultmodel.h \
		calibrateobservermodel.h \
		myhelper.h \
		frmmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o testingdialog.o testingdialog.cpp

testingthread.o: testingthread.cpp testingthread.h \
		mainbussniessview.h \
		patientmodel.h \
		itemmodel.h \
		qc_subitemmodel.h \
		qualitycontrolmodel.h \
		itemparametermodel.h \
		calibratemodel.h \
		sampletypemodel.h \
		testresultmodel.h \
		App.h \
		calibrateobservermodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o testingthread.o testingthread.cpp

testresultmodel.o: testresultmodel.cpp testresultmodel.h \
		itemparametermodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o testresultmodel.o testresultmodel.cpp

whitethread.o: whitethread.cpp whitethread.h \
		mainbussniessview.h \
		patientmodel.h \
		itemmodel.h \
		qc_subitemmodel.h \
		qualitycontrolmodel.h \
		itemparametermodel.h \
		calibratemodel.h \
		sampletypemodel.h \
		testresultmodel.h \
		App.h \
		calibrateobservermodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o whitethread.o whitethread.cpp

moc_calibratedialog.o: moc_calibratedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_calibratedialog.o moc_calibratedialog.cpp

moc_frminput.o: moc_frminput.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_frminput.o moc_frminput.cpp

moc_frmmessagebox.o: moc_frmmessagebox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_frmmessagebox.o moc_frmmessagebox.cpp

moc_mainbussniessview.o: moc_mainbussniessview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainbussniessview.o moc_mainbussniessview.cpp

moc_mainbuttondialog.o: moc_mainbuttondialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainbuttondialog.o moc_mainbuttondialog.cpp

moc_maintenancedialog.o: moc_maintenancedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_maintenancedialog.o moc_maintenancedialog.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_parameterdialog.o: moc_parameterdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_parameterdialog.o moc_parameterdialog.cpp

moc_qextserialbase.o: moc_qextserialbase.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qextserialbase.o moc_qextserialbase.cpp

moc_qprogressdialog.o: moc_qprogressdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qprogressdialog.o moc_qprogressdialog.cpp

moc_qualitycontroldialog.o: moc_qualitycontroldialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qualitycontroldialog.o moc_qualitycontroldialog.cpp

moc_querydialog.o: moc_querydialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_querydialog.o moc_querydialog.cpp

moc_serialportctrl.o: moc_serialportctrl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_serialportctrl.o moc_serialportctrl.cpp

moc_serialportthread.o: moc_serialportthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_serialportthread.o moc_serialportthread.cpp

moc_stopthread.o: moc_stopthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_stopthread.o moc_stopthread.cpp

moc_systemdialog.o: moc_systemdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_systemdialog.o moc_systemdialog.cpp

moc_testingdialog.o: moc_testingdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_testingdialog.o moc_testingdialog.cpp

moc_testingthread.o: moc_testingthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_testingthread.o moc_testingthread.cpp

moc_whitethread.o: moc_whitethread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_whitethread.o moc_whitethread.cpp

qrc_rc.o: qrc_rc.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_rc.o qrc_rc.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

